apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pv.yaml
  - pvc.yaml
  - secrets.yaml
  - configmap.yaml
  - stateful.yaml
  - service.yaml

namespace: postgresql
