apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  POSTGRES_PASSWORD: YjFsbHkwcHMhCg==
  REPLICATION_PASSWORD: YjFsbHkwcHMhCg==
stringData:
  POSTGRES_USER: billy
  POSTGRES_DB: billydb
  REPLICATION_USER: replicationuser
