apiVersion: v1
kind: Service
metadata: 
  name: postgres
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - name: database
      port: 5432
      targetPort: 5432
      nodePort: 32345
